### ISSUE TITLE
Building containers fails

### ISSUE THREAD

**Issue by mtusnio** [CreatorDev/creator-system-test-framework#4]
Following the docker instructions and building the containers results in the following error:

Step 16/18 : RUN make TARGET=minimal-net
 ---> Running in 4562cb6df09f
mkdir obj_minimal-net
  CC        ../AwaLWM2M/core/src/erbium/er-coap.c
  CC        ../AwaLWM2M/core/src/erbium/er-coap-engine.c
  CC        ../AwaLWM2M/core/src/erbium/er-coap-transactions.c
  CC        ../AwaLWM2M/core/src/erbium/er-coap-separate.c
  CC        ../AwaLWM2M/core/src/erbium/er-coap-block1.c
  CC        ../contiki/apps/serial-shell/serial-shell.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_registration.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_bootstrap.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_security_object.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_client_core.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_acl_object.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_server_object.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_serdes.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_tlv.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_opaque.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_plaintext.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_prettyprint.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_tree_builder.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_object_tree.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_observers.c
  CC        ../AwaLWM2M/core/src/client/lwm2m_static.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_list.c
  CC        ../AwaLWM2M/core/src/common/network_abstraction_contiki.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_debug.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_util.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_util_contiki.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_object_store.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_definition.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_attributes.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_tree_node.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_endpoints.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_result.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_types.c
  CC        ../AwaLWM2M/core/src/common/lwm2m_bootstrap_config.c
  CC        ../AwaLWM2M/core/src/common/coap_abstraction_erbium.c
  CC        ../AwaLWM2M/core/src/common/dtls_abstraction_dummy.c
  CC        ../AwaLWM2M/lib/b64/b64.c
  CC        ..//libobjects/lwm2m-client-device-object.c
..//libobjects/lwm2m-client-device-object.c: In function 'executeHandler':
..//libobjects/lwm2m-client-device-object.c:118:5: warning: enumeration value 'AwaOperation_CreateObjectInstance' not handled in switch [-Wswitch]
     switch(operation)
     ^
..//libobjects/lwm2m-client-device-object.c:118:5: warning: enumeration value 'AwaOperation_DeleteObjectInstance' not handled in switch [-Wswitch]
..//libobjects/lwm2m-client-device-object.c:118:5: warning: enumeration value 'AwaOperation_Read' not handled in switch [-Wswitch]
..//libobjects/lwm2m-client-device-object.c:118:5: warning: enumeration value 'AwaOperation_Write' not handled in switch [-Wswitch]
..//libobjects/lwm2m-client-device-object.c:118:5: warning: enumeration value 'AwaOperation_Execute' not handled in switch [-Wswitch]
..//libobjects/lwm2m-client-device-object.c:118:5: warning: enumeration value 'AwaOperation_DeleteResource' not handled in switch [-Wswitch]
  CC        ..//libobjects/lwm2m-client-ipso-digital-input.c
  CC        ..//libobjects/lwm2m-client-ipso-light-control.c
  CC        ..//libobjects/lwm2m-client-ipso-presence.c
  CC        ..//libobjects/lwm2m-client-ipso-temperature.c
  CC        ..//libobjects/lwm2m-client-ipso-set-point.c
  CC        ..//libobjects/lwm2m-client-ipso-barometer.c
  CC        ..//libobjects/lwm2m-client-ipso-power.c
  CC        ..//libobjects/lwm2m-client-ipso-distance.c
  CC        ..//libobjects/lwm2m-client-ipso-concentration.c
  CC        ..//libobjects/lwm2m-client-ipso-humidity.c
  CC        ../contiki/apps/shell/shell.c
  CC        ../contiki/apps/shell/shell-reboot.c
  CC        ../contiki/apps/shell/shell-vars.c
../contiki/apps/shell/shell-vars.c: In function 'process_thread_shell_vars_process':
../contiki/apps/shell/shell-vars.c:80:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
        (unsigned int)symbols[i].value >= SHELL_VARS_RAM_BEGIN &&
        ^
../contiki/apps/shell/shell-vars.c:81:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
        (unsigned int)symbols[i].value <= SHELL_VARS_RAM_END) {
        ^
  CC        ../contiki/apps/shell/shell-ps.c
  CC        ../contiki/apps/shell/shell-blink.c
  CC        ../contiki/apps/shell/shell-text.c
  CC        ../contiki/apps/shell/shell-time.c
../contiki/apps/shell/shell-time.c: In function 'process_thread_shell_repeat_server_process':
../contiki/apps/shell/shell-time.c:161:7: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
   int ret;
       ^
../contiki/apps/shell/shell-time.c: In function 'process_thread_shell_repeat_process':
../contiki/apps/shell/shell-time.c:209:23: warning: variable 'start_time' set but not used [-Wunused-but-set-variable]
   static clock_time_t start_time;
                       ^
../contiki/apps/shell/shell-time.c:205:28: warning: unused variable 'period_left' [-Wunused-variable]
   static int reps, period, period_left;
                            ^
../contiki/apps/shell/shell-time.c: In function 'process_thread_shell_randwait_process':
../contiki/apps/shell/shell-time.c:294:7: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
   int ret;
       ^
  CC        ../contiki/apps/shell/shell-file.c
  CC        ../contiki/apps/shell/shell-run.c
  CC        ../contiki/apps/shell/shell-coffee.c
  CC        ../contiki/apps/shell/shell-power.c
  CC        ../contiki/apps/shell/shell-base64.c
  CC        ../contiki/apps/shell/shell-memdebug.c
../contiki/apps/shell/shell-memdebug.c: In function 'process_thread_shell_poke_process':
../contiki/apps/shell/shell-memdebug.c:74:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   address = (uint8_t *)(int)shell_strtolong(args, &next);
             ^
../contiki/apps/shell/shell-memdebug.c: In function 'process_thread_shell_peek_process':
../contiki/apps/shell/shell-memdebug.c:109:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   address = (uint8_t *)(int)shell_strtolong(args, &next);
             ^
  CC        ../contiki/apps/shell/shell-powertrace.c
  CC        ../contiki/apps/shell/shell-crc.c
  CC        ../contiki/apps/shell/shell-wget.c
  CC        ../contiki/apps/shell/shell-httpd.c
  CC        ../contiki/apps/shell/shell-irc.c
  CC        ../contiki/apps/shell/shell-tcpsend.c
  CC        ../contiki/apps/shell/shell-udpsend.c
  CC        ../contiki/apps/shell/shell-ping.c
  CC        ../contiki/apps/shell/shell-netstat.c
  CC        ../contiki/apps/webserver/http-strings.c
  CC        ../contiki/core/net/ip/psock.c
  CC        ../contiki/core/lib/memb.c
  CC        ../contiki/apps/webserver/httpd-cfs.c
  CC        ../contiki/apps/webserver/urlconv.c
  CC        ../contiki/apps/webserver/webserver-nogui.c
  CC        ../contiki/apps/webbrowser/webclient.c
  CC        ../contiki/apps/webbrowser/http-user-agent-string.c
  CC        ../contiki/apps/irc/ircc.c
  CC        ../contiki/apps/irc/ircc-strings.c
  CC        ../contiki/apps/telnet/telnet.c
  CC        ../contiki/apps/powertrace/powertrace.c
../contiki/apps/powertrace/powertrace.c: In function 'powertrace_print':
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'uint32_t {aka unsigned int}' [-Wformat=]
   printf("%s %lu P %d.%d %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu (radio %d.%02d%% / %d.%02d%% tx %d.%02d%% / %d.%02d%% listen %d.%02d%% / %d.%02d%%)\n",
          ^
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 8 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 9 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 10 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 11 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 12 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 13 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 14 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 15 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 16 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 17 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:118:10: warning: format '%lu' expects argument of type 'long unsigned int', but argument 18 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'uint32_t {aka unsigned int}' [-Wformat=]
     printf("%s %lu SP %d.%d %lu %u %u %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu (proto %u(%u) radio %d.%02d%% / %d.%02d%%)\n",
            ^
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 9 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 10 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 11 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 12 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 13 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 14 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 15 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 16 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 17 has type 'uint32_t {aka unsigned int}' [-Wformat=]
../contiki/apps/powertrace/powertrace.c:162:12: warning: format '%lu' expects argument of type 'long unsigned int', but argument 18 has type 'uint32_t {aka unsigned int}' [-Wformat=]
  CC        ../contiki/apps/shell/shell-dsc.c
  CC        ../contiki/apps/webserver/webserver-dsc.c
  CC        ../contiki/apps/webbrowser/www-dsc.c
  CC        ../contiki/apps/irc/irc-dsc.c
  CC        ../contiki/apps/telnet/telnet-dsc.c
  CC        ../contiki/platform/minimal-net/./contiki-main.c
  CC        ../contiki/platform/minimal-net/./clock.c
  CC        ../contiki/core/dev/leds.c
  CC        ../contiki/platform/minimal-net/./leds-arch.c
  CC        ../contiki/core/cfs/cfs-posix.c
  CC        ../contiki/core/cfs/cfs-posix-dir.c
  CC        ../contiki/core/loader/dlloader.c
  CC        ../contiki/cpu/native/net/tapdev-drv.c
  CC        ../contiki/cpu/native/net/tapdev.c
  CC        ../contiki/cpu/native/net/tapdev6.c
../contiki/cpu/native/net/tapdev6.c: In function 'tapdev_init':
../contiki/cpu/native/net/tapdev6.c:334:3: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
   system(buf);
   ^
  CC        ../contiki/cpu/native/./mtarch.c
  CC        ../contiki/cpu/native/./rtimer-arch.c
  CC        ../contiki/core/loader/elfloader-stub.c
  CC        ../contiki/cpu/native/./watchdog.c
  CC        ../contiki/cpu/native/dev/eeprom.c
  CC        ../contiki/core/sys/autostart.c
  CC        ../contiki/core/sys/ctimer.c
  CC        ../contiki/core/sys/energest.c
  CC        ../contiki/core/sys/arg.c
  CC        ../contiki/core/sys/stimer.c
  CC        ../contiki/core/sys/etimer.c
  CC        ../contiki/core/sys/compower.c
  CC        ../contiki/core/sys/process.c
  CC        ../contiki/core/sys/rtimer.c
  CC        ../contiki/core/sys/mt.c
  CC        ../contiki/core/sys/procinit.c
  CC        ../contiki/core/sys/timer.c
  CC        ../contiki/core/dev/serial-line.c
  CC        ../contiki/core/dev/slip.c
  CC        ../contiki/core/dev/nullradio.c
  CC        ../contiki/core/lib/settings.c
  CC        ../contiki/core/lib/crc16.c
  CC        ../contiki/core/lib/me.c
  CC        ../contiki/core/lib/sensors.c
  CC        ../contiki/core/lib/ifft.c
  CC        ../contiki/core/lib/me_tabs.c
  CC        ../contiki/core/lib/ccm-star.c
  CC        ../contiki/core/lib/mmem.c
  CC        ../contiki/core/lib/list.c
  CC        ../contiki/core/lib/gcr.c
  CC        ../contiki/core/lib/aes-128.c
  CC        ../contiki/core/lib/trickle-timer.c
  CC        ../contiki/core/lib/print-stats.c
  CC        ../contiki/core/lib/petsciiconv.c
  CC        ../contiki/core/lib/random.c
  CC        ../contiki/core/lib/assert.c
  CC        ../contiki/core/lib/ringbuf.c
  CC        ../contiki/core/net/ipv6/uip-icmp6.c
  CC        ../contiki/core/net/ipv6/uip-ds6.c
  CC        ../contiki/core/net/ipv6/uip-ds6-route.c
  CC        ../contiki/core/net/ipv6/uip6.c
  CC        ../contiki/core/net/ipv6/uip-ds6-nbr.c
  CC        ../contiki/core/net/ipv6/uip-nd6.c
  CC        ../contiki/core/net/ipv6/sicslowpan.c
  CC        ../contiki/core/net/ip/slipdev.c
  CC        ../contiki/core/net/ip/dhcpc.c
  CC        ../contiki/core/net/ip/uip-packetqueue.c
  CC        ../contiki/core/net/ip/tcp-socket.c
  CC        ../contiki/core/net/ip/uip-debug.c
  CC        ../contiki/core/net/ip/ip64-addr.c
  CC        ../contiki/core/net/ip/uip-udp-packet.c
  CC        ../contiki/core/net/ip/tcpip.c
  CC        ../contiki/core/net/ip/resolv.c
../contiki/core/net/ip/resolv.c: In function 'mdns_write_announce_records':
../contiki/core/net/ip/resolv.c:532:23: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
       uint8_t* aPtr = &uip_ds6_if.addr_list[i].ipaddr;
                       ^
  CC        ../contiki/core/net/ip/uip-nameserver.c
  CC        ../contiki/core/net/ip/uip-split.c
  CC        ../contiki/core/net/ip/udp-socket.c
  CC        ../contiki/core/net/ip/simple-udp.c
  CC        ../contiki/core/net/ip/uiplib.c
  CC        ../contiki/core/net/queuebuf.c
  CC        ../contiki/core/net/nbr-table.c
  CC        ../contiki/core/net/packetbuf.c
  CC        ../contiki/core/net/netstack.c
  CC        ../contiki/core/net/linkaddr.c
cp ../contiki/tools/empty-symbols.c symbols.c
cp ../contiki/tools/empty-symbols.h symbols.h
  CC        symbols.c
  AR        contiki-minimal-net.a
  CC        lwm2m-client-contiki-test.c
lwm2m-client-contiki-test.c:57:38: fatal error: lwm2m-client-flow-object.h: No such file or directory
compilation terminated.
make: *** [lwm2m-client-contiki-test.co] Error 1
../contiki/Makefile.include:260: recipe for target 'lwm2m-client-contiki-test.co' failed
The command '/bin/sh -c make TARGET=minimal-net' returned a non-zero code: 2

**Comment by boyvinall** [comment]
I think it's probably just a case of removing that `#include` line. I did previously update the [lwm2m-contiki](https://github.com/CreatorDev/lwm2m-contiki) repo to remove those old objects. I guess I didn't do a fresh checkout after that. PRs gratefully accepted 😃

**Comment by mtusnio** [comment]
Removed here - https://github.com/CreatorDev/lwm2m-contiki/pull/2 - needs a merge before I can update the submodule

**Comment by boyvinall** [comment]
Thanks, I've merged that one now.
